const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 4,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-1.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-2.jpg',
      isFavorite: true,
      isCompare: false,
      oldPrice: 45,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-3.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 50,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-4.jpg',
      isFavorite: true,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-5.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-6.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 35,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-7.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-8.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-2.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-1.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-4.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-3.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-6.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-5.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-8.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-7.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-8.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-7.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-6.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-5.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-4.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-3.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-2.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/beds/bed-1.jpg',
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'definitely-not-cursed-chair-1',
      name: 'Definitely Not Cursed Chair 1',
      category: 'chair',
      price: 60,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/chairs/chair-1.jpeg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 666,
    },
    {
      id: 'definitely-not-cursed-chair-2',
      name: 'Definitely Not Cursed Chair 2',
      category: 'chair',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/chairs/chair-2.jpeg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'iron-throne-3',
      name: 'Iron Throne 3',
      category: 'chair',
      price: 50,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/chairs/chair-3.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'porcelain-throne-4',
      name: 'Throne 4',
      category: 'chair',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/chairs/chair-4.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'definitely-not-cursed-chair-5',
      name: 'Definitely Not Cursed Chair 5',
      category: 'chair',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/chairs/chair-5.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'definitely-not-cursed-chair-6',
      name: 'Definitely Not Cursed Chair 6',
      category: 'chair',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/chairs/chair-6.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'definitely-not-cursed-chair-7',
      name: 'Definitely Not Cursed Chair 7',
      category: 'chair',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/chairs/chair-7.png',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'definitely-not-cursed-chair-8',
      name: 'Definitely Not Cursed Chair 8',
      category: 'chair',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/chairs/chair-8.jpeg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'sofa-1',
      name: 'Comfortable Sofa 1',
      category: 'sofa',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/sofas/sofa-1.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'sofa-2',
      name: 'Comfortable Sofa 2',
      category: 'sofa',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/sofas/sofa-2.webp',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'sofa-3',
      name: 'Comfortable Sofa 3',
      category: 'sofa',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/sofas/sofa-3.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'sofa-4',
      name: 'Comfortable Sofa 4',
      category: 'sofa',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/sofas/sofa-4.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'sofa-5',
      name: 'Comfortable Sofa 5',
      category: 'sofa',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/sofas/sofa-5.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'table-1',
      name: 'Comfortable Table 1',
      category: 'table',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/tables/table-1.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'table-2',
      name: 'Comfortable Table 2',
      category: 'table',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/tables/table-2.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'table-3',
      name: 'Comfortable Table 3',
      category: 'table',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/tables/table-3.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'table-4',
      name: 'Comfortable Table 4',
      category: 'table',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/tables/table-4.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'table-5',
      name: 'Comfortable Table 5',
      category: 'table',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/tables/table-5.webp',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'dining-1',
      name: 'Spork',
      category: 'dining',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/dining/spork.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'dining-2',
      name: 'Spork',
      category: 'dining',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/dining/spork.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'dining-3',
      name: 'Spork',
      category: 'dining',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/dining/spork.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'dining-4',
      name: 'Spork',
      category: 'dining',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/dining/spork.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
    {
      id: 'dining-5',
      name: 'Spork',
      category: 'dining',
      price: 30,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      image: process.env.PUBLIC_URL + '/images/dining/spork.jpg',
      isFavorite: false,
      isCompare: false,
      oldPrice: 60,
    },
  ],
  cart: {
    products: [],
  },
  viewport: { type: 'desktop' },
};

export default initialState;
